services:
  psodox_postgres:
    container_name: mennen_cloud_development_postgres
    build:
      context: ../build/postgres
    environment:
      POSTGRES_PASSWORD: psodox
      POSTGRES_USER: psodox
      POSTGRES_DB: psodox